---
- name: Remove deprecated Ansible PPA
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible
    state: absent

- name: Remove deprecated Go PPA
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:longsleep/golang-backports
    state: absent

- name: Remove existing Liquibase repository before apt upgrade
  become: yes
  ansible.builtin.deb822_repository:
    name: liquibase
    state: absent

- name: Remove GitHub CLI repository (disabled due to repo issues)
  become: yes
  ansible.builtin.deb822_repository:
    name: github-cli
    state: absent

- name: Update and upgrade apt packages
  become: yes
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install packages
  become: yes
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: latest

- name: Remove dependencies that are no longer required
  become: yes
  ansible.builtin.apt:
    autoremove: yes
