---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install packages
  become: yes
  apt:
    name: "{{ apt_packages }}"
    state: latest

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes