---
- name: Randomise those cow in bashrc!
  ansible.builtin.lineinfile:
    path: "$HOME/.bashrc"
    line: 'export ANSIBLE_COW_SELECTION=random'
    state: present

- name: Randomise those cows in zshrc!
  ansible.builtin.lineinfile:
    path: "$HOME/.zshrc"
    line: 'export ANSIBLE_COW_SELECTION=random'
    state: present
