---
- name: Add GitHub CLI repository using key from URL
  become: yes
  ansible.builtin.deb822_repository:
    name: github-cli
    types: deb
    uris: https://cli.github.com/packages
    suites: '{{ ansible_distribution_release }}'
    components: stable
    architectures: amd64
    signed_by: https://cli.github.com/packages/githubcli-archive-keyring.gpg

- name: Install GitHub CLI package
  become: yes
  ansible.builtin.apt:
    name: gh
    state: latest