---
# https://go.dev/wiki/Ubuntu
- name: Add PPA repository for golang
  become: yes
  apt_repository:
    repo: ppa:longsleep/golang-backports

- name: Update apt packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install golang
  become: yes
  ansible.builtin.apt:
    name: golang-go
    state: latest
