---
# Install the Ubuntu-packaged Go toolchain.
- name: Install golang
  become: yes
  ansible.builtin.apt:
    name: golang-go
    state: present

- name: Add Go bin directory to PATH in bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/go/bin:$PATH"'
    state: present

- name: Add Go bin directory to PATH in zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$HOME/go/bin:$PATH"'
    state: present