---
# https://docs.liquibase.com/start/install/liquibase-linux-debian-ubuntu.html1
- name: Add Liquibase apt repository using key from URL
  become: yes
  ansible.builtin.deb822_repository:
    name: liquibase
    types: deb
    uris: https://repo.liquibase.com
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://repo.liquibase.com/liquibase.asc

- name: Update apt packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install Liquibase CLI
  become: yes
  ansible.builtin.apt:
    name: liquibase
    state: latest