---
# https://docs.liquibase.com/start/install/liquibase-linux-debian-ubuntu.html
- name: Download Liquibase apt signing key
  become: yes
  ansible.builtin.get_url:
    url: https://repo.liquibase.com/liquibase.asc
    dest: /usr/share/keyrings/liquibase.asc
    mode: '0644'

- name: Add Liquibase apt repository
  become: yes
  ansible.builtin.deb822_repository:
    name: liquibase
    types: deb
    uris: https://repo.liquibase.com
    suites: stable
    components: main
    architectures: amd64
    signed_by: /usr/share/keyrings/liquibase.asc

- name: Update apt packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install Liquibase CLI
  become: yes
  ansible.builtin.apt:
    name: liquibase
    state: present