- import_tasks: apt.yml
- import_tasks: bash.yml
- import_tasks: node.yml
- import_tasks: gh.yml
- import_tasks: go.yml
- import_tasks: npm.yml
- import_tasks: aws.yml
- import_tasks: azure.yml
- import_tasks: cows.yml
