---
# https://ngrok.com/download
- name: Download ngrok
  become: yes
  ansible.builtin.unarchive:
    src: https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/ngrok
