---
- name: Add an apt signing key for ngrok
  become: true
  apt_key:
    url: https://ngrok-agent.s3.amazonaws.com/ngrok.asc
    state: present

- name: Add apt repository for ngrok
  become: true
  apt_repository:
    repo: deb https://ngrok-agent.s3.amazonaws.com buster main
    filename: ngrok.list
    state: present

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install ngrok
  become: true
  apt:
    name: ngrok
    state: latest
