---
- name: Add a source file for the official Node.js 10.x repo
  shell:
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

- name: Install Node.js 10.x
  become: yes
  apt:
    name: nodejs
    state: latest
