---
- name: Download nodesource setup script
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/nsolid_setup_deb.sh
    dest: /tmp/nsolid_setup_deb.sh
    mode: '0500'

- name: Run nodesource setup script
  become: yes
  ansible.builtin.shell: /tmp/nsolid_setup_deb.sh {{ node_version }}
  args:
    creates: /usr/share/keyrings/nodesource.gpg

- name: Install Node.js {{ node_version }}
  become: yes
  ansible.builtin.apt:
    name: nodejs
