---
# https://github.com/nodesource/distributions
- name: Download nodesource setup script for Node.js LTS
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/setup_lts.x
    dest: /tmp/setup_lts.x
    mode: '0500'

- name: Run nodesource setup script
  become: yes
  ansible.builtin.shell: /tmp/setup_lts.x

- name: Install Node.js LTS
  become: yes
  ansible.builtin.apt:
    name: nodejs
