apt_packages:
  - curl
  - zip
  - jq
  - cowsay
  - python3-debian
  - python3-pip
  - python3-venv
  - zsh
  - default-jre
  - tmpreaper
  - qdirstat

node_packages:
  - "@microsoft/rush"
  - aws-cdk
