#!/bin/bash

# Check that the AWS profile parameter has been provided
if [ -z "$1" ]; then
    echo "usage: $0 [aws_profile]"
    exit 1;
fi;

# Check that the pre-requisite commands exist
if ! hash aws 2>/dev/null
then
    echo "'aws' was not found"
    exit 1
fi
if ! hash jq 2>/dev/null
then
    echo "'jq' was not found"
    exit 1
fi

# Clear the AWS CLI cached credentials
rm ~/.aws/cli/cache/*.json

# Run the 'aws s3 ls' command to allow MFA authentication
if ! aws s3 ls --profile $1
then
    exit 1
fi

# Get the required AWS credentials from the AWS CLI cache
AccessKeyId=$(cat ~/.aws/cli/cache/*.json | jq '.Credentials.AccessKeyId')
SecretAccessKey=$(cat ~/.aws/cli/cache/*.json | jq '.Credentials.SecretAccessKey')
SessionToken=$(cat ~/.aws/cli/cache/*.json | jq '.Credentials.SessionToken')

# Echo the export commands required to set the environment variables
# to authenticate via MFA when using the CDK CLI
echo -e "\nexport AWS_ACCESS_KEY_ID=${AccessKeyId}\nexport AWS_SECRET_ACCESS_KEY=${SecretAccessKey}\nexport AWS_SESSION_TOKEN=${SessionToken}\n"

echo "Paste the authentication environment variables"
